// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq59YnBX-23IWBS8T9SgDmuMeXdyBFmP0',
    appId: '1:241826805287:web:e0c2ff8d84d14fa3008002',
    messagingSenderId: '241826805287',
    projectId: 'todokraftbase',
    authDomain: 'todokraftbase.firebaseapp.com',
    storageBucket: 'todokraftbase.appspot.com',
    measurementId: 'G-5F5JH98W6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC80y3zPywe6H5DyKLog7GE6DkMx1tYVI',
    appId: '1:241826805287:android:673d55acfe5970b4008002',
    messagingSenderId: '241826805287',
    projectId: 'todokraftbase',
    storageBucket: 'todokraftbase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UEHliIbGjnULg4n-FRMz4Z5g4qoXODk',
    appId: '1:241826805287:ios:554e948d60bcfb74008002',
    messagingSenderId: '241826805287',
    projectId: 'todokraftbase',
    storageBucket: 'todokraftbase.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0UEHliIbGjnULg4n-FRMz4Z5g4qoXODk',
    appId: '1:241826805287:ios:554e948d60bcfb74008002',
    messagingSenderId: '241826805287',
    projectId: 'todokraftbase',
    storageBucket: 'todokraftbase.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq59YnBX-23IWBS8T9SgDmuMeXdyBFmP0',
    appId: '1:241826805287:web:b17cda86dcf34e13008002',
    messagingSenderId: '241826805287',
    projectId: 'todokraftbase',
    authDomain: 'todokraftbase.firebaseapp.com',
    storageBucket: 'todokraftbase.appspot.com',
    measurementId: 'G-6G3QRKSHT2',
  );
}
